
DATASET:
  NYU_PATH: '/media/zhoukanglei/Windows/chen/pycharm/dataset/dataset'
  TIM_TREMOR_PATH: '/media/zhoukanglei/Windows/ZKL/Data/TIM-Tremor/data/'

  NYU_TRAIN_NUM: 72757
  NYU_TEST_NUM: 8252
  NYU_KINECT_NUM: 3

  NOISE: 'Uniform'

  SIGMA_O: 0.1
  SIGMA_S: 0.1
  BETA: 50
  TREMOR_AMPLITUDE: 6
  TREMOR_CYCLE: 5

ATTENTION:
  - 'A'
  - 'A+M'
  - 'A*M'
  - 'A+B+C'

MODEL:
  OUTPUT_LOG_PATH: './output/log/tensorboard'
  OUTPUT_HISTORY_PATH: './output/history'

  OPT_IDX: 9

  VALIDATION_RATE: 0.15
  T_SIZE: 36

  MAX_EPOCH: 300
  PATIENCE: 10
  MIN_LR: 1e-7

OPTION: False